// Generated by Copilot: Adding TensorZero handler to integrate TensorZero with TorchServe's backend system
#pragma once

#include "base_handler.hh"
#include "tensorzero/tensorzero.h"

namespace torchserve
{

  class TensorZeroHandler : public BaseHandler
  {
  public:
    TensorZeroHandler() = default;
    ~TensorZeroHandler() override = default;

    void initialize(const std::string &model_path) override;
    ts_error_message inference(const RequestContext &context, ResponseContext &response) override;
    void preprocess(const RequestContext &context) override;
    void postprocess(ResponseContext &response) override;

  private:
    std::unique_ptr<tensorzero::Model> model_;
  };