name: CI CPU

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request### Solution:
1. **Install `numactl`**:
   - Ensure `numactl` is installed on your runner environments, particularly for macOS.

### Updated Workflow:
Update your:
    branches:
      - master
  merge_group:

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number `.github/workflows/ci_cpu.yml` to include the installation of `numactl` for macOS.

```yaml
name: CI CPU

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - || github.ref }}
  cancel-in-progress: true

jobs:
  ci-cpu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        master
  merge_group:

concurrency:
  group: ci-c os: [ubuntu-20.04, macos-latest]
    steps:
      - name: Setup Python for M1
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@pu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
 v5
        with:
          python-version: '3.10'
          architecture cancel-in-progress: true

jobs:
  ci-cpu:
    runs-on: arm64
      - name: Setup Python for all other OS
        if: matrix.os != 'macos-latest'
        uses: actions/setup-python@v5
        with: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
    steps:
      - name: Setup Python for M:
          python-version: '3.9'
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup1
        if: matrix.os == 'macos-latest'
        uses:-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@ actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: arm64
      - name: Setup Python for all other OS
        if: matrix.os != 'macos-latest'
        uses: actions/setup-python@v5
        with:
          python-version:v3
        with:
          submodules: recursive
      - name: Install numactl on Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y numactl
      - name: Install dependencies
        run '3.9'
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version:: |
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Torchserve Sanity
 '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
        with:
          sub        env:
          TS_MAC_ARM64_CPU_ONLY: ${{ matrix.os == 'macos-latest' && 'True' || 'False' }}
modules: recursive
      - name: Install numactl on        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 60
          max_attempts: macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install numactl
      - name 3
          retry_on: error
          command: |
            python torchserve_sanity.py
      # Any coverage.xml will be picked up by this step
      #: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Torchserve Sanity
        env:
          Just make sure each coverage.xml is in a different folder
 TS_MAC_ARM64_CPU_ONLY: ${{ matrix.os == 'macos-latest' && 'True' || 'False' }}
        uses: nick      - name: Upload codecov
        if: matrix.os == 'ubuntu-20.04'
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
