name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate wiki content
        run: |
          python generate_wiki_content.py

      - name: Update wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          cd $(basename ${{ github.repository }}.wiki .git)
          cp -r ../wiki/* .
          git add .
          git commit -m "Update wiki with latest changes"
          git push
